# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

version_code = ENV['CI_JOB_ID'].to_i == 0 ? 1 : ENV['CI_JOB_ID'].to_i

release_notes = changelog_from_git_commits(
    commits_count: 10,
    pretty: "✨ %s%nBy %an, %ar%n",
    date_format: "short",
    match_lightweight_tag: false,
    merge_commit_filtering: "exclude_merges"
)

default_platform(:ios)

platform :ios do

    before_all do
        ENV["SLACK_URL"] = ENV['SLACK_UPDATES']
        ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    end

    desc "Runs all the tests"
        lane :test do
        # run tests
    end

    desc "Submit a new Beta Build to Firebase App Distribution"
    lane :beta do
    end

    desc "Deploy a new version to the App Store"
    lane :deploy do
    end
end
